# Generated by Django 3.2.16 on 2022-10-06 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='subject',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='create_by',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='create_dt',
            new_name='created_dt',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='create_by',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='create_dt',
            new_name='created_dt',
        ),
    ]
