# Generated by Django 3.2.16 on 2022-10-06 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_auto_20221006_0135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='board',
            new_name='topic',
        ),
    ]
